In [87]:
# importamos librerías a utilizar
import numpy as np
import pymongo

In [118]:
# conexión a la bd
from pymongo import MongoClient
from urllib.parse import quote_plus
import pandas as pd
from pandas.io.json import json_normalize

mongo_user = "dev"
mongo_password = "dev12345"
mongo_url = "ds123454.mlab.com:23454/macri-discursos"
monto_url_stats = "ds115283.mlab.com:15283/discursos-stats"
host = "mongodb://ds123454.mlab.com"
port = 23454
db_name = "macri-discursos"

uri =  "mongodb://{}:{}@{}".format(quote_plus(mongo_user), quote_plus(mongo_password), mongo_url)

client = MongoClient(uri)
db = client[db_name]

collections = ['ngrams_5_counts', 'ngrams_6_counts', 'ngrams_7_counts', 'speeches', 'speeches_stats', 'wordcounts_totals']

In [110]:
# obtenemos los wordcounts totales y realizamos un preprocesamiento de la info
wordcounts_totals = list(db.wordcounts_totals.find())
wordcounts_totals = pd.DataFrame(wordcounts_totals).drop('_id', axis=1)
wordcounts_totals = wordcounts_totals.set_index('word')

In [111]:
# obtenemos las palabras que agregamos a la entrega, para visualizarlas

wordcounts_totals.sort_values('word_count', ascending = False, inplace=True)
# print(wordcounts_totals.head(100))
# for i in wordcounts_totals[['word', 'word_count']].values: print(i)

wordcounts_totals.loc[["argentina","argentinos","trabajo","mundo","ustedes","juntos","verdad","compromiso"]]

            word_count
word
argentina         2521
argentinos        1839
trabajo           1621
mundo             1505
ustedes           1378
juntos            1029
verdad             909
compromiso         458

In [112]:
#obtenemos las 3 colecciones de ngrams, y las limitamos a 10 elementos. mongodb-query
n5, n6, n7 = [list(db[coll].find().sort([('counter', pymongo.DESCENDING)]).limit(10)) for coll in ['ngrams_5_counts', 'ngrams_6_counts', 'ngrams_7_counts']]

In [113]:
# preprocesamiento de las 3 colecciones 
n5, n6, n7 = [ pd.DataFrame(d).drop('_id', axis=1).set_index('ngram') for d in [n5, n6, n7] ]

In [117]:
n5

                              counter
ngram
la ciudad de buenos aires         132
y eso es lo que                    96
macri en el acto de                67
la provincia de buenos aires       66
que somos capaces de hacer         59
de un día para el                  56
que tiene que ver con              56
un día para el otro                56
lo que somos capaces de            54
de la ciudad de buenos             50

In [115]:
n6

                                           counter
ngram
de un día para el otro                          56
lo que somos capaces de hacer                   51
de la ciudad de buenos aires                    50
en la ciudad de buenos aires                    48
plan de infraestructura más importante de       28
en la provincia de buenos aires                 26
el plan de infraestructura más importante       26
provincia de buenos aires buenos días           25
en lo que somos capaces de                      24
la ciudad de buenos aires y                     23

In [116]:
n7

                                                    counter
ngram
el plan de infraestructura más importante de             26
en lo que somos capaces de hacer                         24
gobierno de la ciudad de buenos aires                    21
de un día para el otro pero                              21
de infraestructura más importante de nuestra hi...       16
plan de infraestructura más importante de nuestra        16
el sector público y el sector privado                    15
de buenos aires buenos días a todos                      15
lo que ustedes son capaces de hacer                      15
que somos capaces de hacer los argentinos                14